export const decks = [
  {
    title: "Basic Words 1",
    alt: "Basic Words 1",
    src: "basic-words-i",
    type: "basic",
  },
  {
    title: "Basic Words 2",
    alt: "Basic Words 2",
    src: "basic-words-ii",
    type: "basic",
  },
  {
    title: "Basic Words 3",
    alt: "Basic Words 3",
    src: "basic-words-3",
    type: "basic",
  },
  {
    title: "Basic Words 4",
    alt: "Basic Words 4",
    src: "basic-words-4",
    type: "basic",
  },
  {
    title: "Basic Words 5",
    alt: "Basic Words 5",
    src: "basic-words-5",
    type: "basic",
  },
  {
    title: "Basic Words 6",
    alt: "Basic Words 6",
    src: "basic-words-6",
    type: "basic",
  },
  {
    title: "Basic Words 7",
    alt: "Basic Words 7",
    src: "basic-words-7",
    type: "basic",
  },
  {
    title: "Common Words 1",
    alt: "Common Words 1",
    src: "high-frequency-words",
    type: "common",
  },
  {
    title: "Common Words 2",
    alt: "Common Words 2",
    src: "common-words-2",
    type: "common",
  },
  {
    title: "Common Words 3",
    alt: "Common Words 3",
    src: "common-words-3",
    type: "common",
  },
  {
    title: "Common Words 4",
    alt: "Common Words 4",
    src: "common-words-4",
    type: "common",
  },
  {
    title: "Common Words 5",
    alt: "Common Words 5",
    src: "common-words-5",
    type: "common",
  },
  {
    title: "Common Words 6",
    alt: "Common Words 6",
    src: "common-words-6",
    type: "common",
  },
  {
    title: "Advanced Words 1",
    alt: "Advanced Words 1",
    src: "advanced-words-i",
    type: "advanced",
  },
  {
    title: "Advanced Words 2",
    alt: "Advanced Words 2",
    src: "advanced-words-ii",
    type: "advanced",
  },
  {
    title: "Advanced Words 3",
    alt: "Advanced Words 3",
    src: "advanced-words-3",
    type: "advanced",
  },
  {
    title: "Advanced Words 4",
    alt: "Advanced Words 4",
    src: "advanced-words-4",
    type: "advanced",
  },
  {
    title: "Advanced Words 5",
    alt: "Advanced Words 5",
    src: "advanced-words-5",
    type: "advanced",
  },
  {
    title: "Advanced Words 6",
    alt: "Advanced Words 6",
    src: "advanced-words-6",
    type: "advanced",
  },
  {
    title: "Advanced Words 7",
    alt: "Advanced Words 7",
    src: "advanced-words-7",
    type: "advanced",
  },
];
